### ISSUE TITLE
移动端H5页面下拉查询组件不显示

### ISSUE THREAD

**Issue by lm798880844** [springreport/springreport#106]
查询组件为下拉单选时，网页端显示正常，H5页面查询信息不显示
![7f8e7d2aa49f0ffe964d3c33665ac8c](https://github.com/user-attachments/assets/f9ef7ce3-6349-41a1-a65e-866c36846781)
![image](https://github.com/user-attachments/assets/943d4302-9e7b-4cb0-aefd-41f12af41e95)
![image](https://github.com/user-attachments/assets/70db5961-7fc3-4b19-a53a-22677a87be98)

**Comment by springreport** [comment]
这个问题我找时间确认

**Comment by springreport** [comment]
已修复
