### ISSUE TITLE
word模板单元格背景颜色

### ISSUE THREAD

**Issue by LennorLv** [springreport/springreport#119]
![image](https://github.com/user-attachments/assets/8b04b0bc-99f5-4de4-824a-01d2716e42cd)
目前canvas editor 有提供单元格背景色的方法，希望可以集成到word工具栏里

额外的需求：
1. 表格框架样式，粗细及颜色
2. 目录生成

另外可能是editor的bug ，word中设置的标题，但是在导出word里成了正文

**Comment by springreport** [comment]
1.单元格背景颜色已经支持

**Comment by springreport** [comment]
目录生成调研了一下，不太好生成，暂时先搁置了，后续会再继续研究一下
