### ISSUE TITLE
word 设计器中表格设置部分框线时，在预览时表格框线全部不显示

### ISSUE THREAD

**Issue by LennorLv** [springreport/springreport#126]
![image](https://github.com/user-attachments/assets/e8336ea4-1a6b-4978-85d3-d27d2f036950)

预览后不显示框线
![image](https://github.com/user-attachments/assets/db66c650-69a9-46b6-87c5-e06382fff421)

**Comment by springreport** [comment]
框线目前只支持全部框线和无框线，不支持部分框线设置
