### ISSUE TITLE
【bug】word表格预览不明原因高度过高

### ISSUE THREAD

**Issue by LennorLv** [springreport/springreport#129]
设计器
<img width="731" alt="image" src="https://github.com/user-attachments/assets/8d98a0cd-02c9-444b-bccd-923d9245df74">

预览时，行过高
<img width="1367" alt="image" src="https://github.com/user-attachments/assets/29017359-2dc9-41e9-bc8d-195d299ce5c3">

**Comment by springreport** [comment]
这是因为数据集+属性名太长了，导致高度过高，因为考虑到实际情况中会有表格高度需要比较高情况，比如填写意见等，所以设置了一个阈值，>4倍正常单元格高度的将会保持这个高度，所以你这个高度就会比较高
