### ISSUE TITLE
word模板编辑时是否可以支持拖拉拽的形式

### ISSUE THREAD

**Issue by 1310020007** [springreport/springreport#131]
当前模板编辑时，是使用的复制粘贴形式，能使增加拖拉拽的形式，拖动到模板编辑位置即可，此时数据集使用包括复制粘贴和拖拉拽，使用就很方便

**Comment by springreport** [comment]
word需要研究一下看看，大概率是不支持的，所以我当时采用了复制 粘贴的形式，不过也可以通过其他方式进行优化改进，可以尝试直接添加到当前光标所在的位置，不需要进行复制粘贴操作

**Comment by LennorLv** [comment]
直接插入光标位置就可以

**Comment by springreport** [comment]
下个版本支持光标位置插入数据
