### ISSUE TITLE
【bug】word字体设置“雅黑”，导出word为宋体

### ISSUE THREAD

**Issue by LennorLv** [springreport/springreport#132]
![image](https://github.com/user-attachments/assets/04683c65-0018-4cf3-af02-4fd5a72889b0)
设计时表格里预览是雅黑，导出来不一致

**Comment by springreport** [comment]
未复现出来，代码我检查了，如果未手动设置字体默认就是微软雅黑字体，导出来的也是正常的微软雅黑。
请自己再确认一下是否手动设置过字体
