### ISSUE TITLE
协同文档权限设置区域编辑可以按部门进行管理&添加表单访问权限&浏览器页面的标题

### ISSUE THREAD

**Issue by YuAnAan** [springreport/springreport#33]
1、在点击添加权限中显示类似于二级菜单，可以点击部门选择框后全选该部门下的所有人员，也可以特定取消某些人员。
2、目前协同表单对于访问用户是全开放的，针对不同用户设置可访问，可编辑等着操作权限，可以将表单绑定到部门下进行访问限制，可以是单部门可以是多部门。
3、在点击表单后，跳转到新的浏览器窗口，可以显示该表单名称作为浏览器页面的标题作为方便区分。

**Comment by springreport** [comment]
问题1和2都可以根据自己的需求进行开发，我这边暂时没有做太多的控制，有时候也想不到这么应用场景，只能实现一些基本的功能，然后用户根据自己的需求定制化修改即可
问题3将会尝试进行优化

**Comment by springreport** [comment]
问题3已经优化
