### ISSUE TITLE
图表设计显示有误

### ISSUE THREAD

**Issue by damon91** [springreport/springreport#43]
![image](https://github.com/user-attachments/assets/a09414b6-8ae0-47f1-8e76-b4cf87994054)
这里应该是：设选中项第一列为标题

**Comment by springreport** [comment]
这个地方并没有实际作用，请参照文档视频来具体的操作，文档地址：https://gitee.com/springreport/springreport/wikis/pages?sort_id=11336155&doc_id=5747656
