### ISSUE TITLE
SpringReport-ui-vue3 打包内存溢出

### ISSUE THREAD

**Issue by abciop** [springreport/springreport#54]
1、用yarn命令对项目进行打包时，出现如下的错误信息 “FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory” 

2、 已经按帮助文档 https://www.cnblogs.com/qubernet/p/18202023 安装相关插件了，还是不行

![bebb0d05f0bb41b39f98936f6b55e651](https://github.com/user-attachments/assets/2eccb8d8-df77-4f28-955b-1dbb0e1da835)

**Comment by springreport** [comment]
已优化
