### ISSUE TITLE
报表设计 数据源为api类型时，修改参数，提交报错

### ISSUE THREAD

**Issue by kittywu66** [springreport/springreport#70]
![00171eb0614972d5a2f9cc901235449](https://github.com/user-attachments/assets/ca696291-2b80-4f24-9ed2-e3d61bbee85b)
初次添加时，没有sql类型，点编辑，进来，自动就有sql类型，并且默认选中标准sql，导致提交报错

**Comment by springreport** [comment]
vue2和vue3版本都未复现出来，请拉取最新代码重新试一下

**Comment by springreport** [comment]
填报报表的问题，已修复
