### ISSUE TITLE
数据集的参数配置，参数类型为日期，并且带有默认值，保存好点击预览，日期选择框没有把默认值选中

### ISSUE THREAD

**Issue by luoquansheng** [springreport/springreport#72]
![image](https://github.com/user-attachments/assets/c562d4b5-a529-4791-be5c-afdc0dbd632d)
![image](https://github.com/user-attachments/assets/2db74407-d587-4277-8c6b-faf391ecec2f)

**Comment by springreport** [comment]
默认值请按照规则设置，下方备注都有，也可以看文档https://gitee.com/springreport/springreport/wikis/pages?sort_id=11336097&doc_id=5747656

**Comment by luoquansheng** [comment]
好的
