### ISSUE TITLE
多个数据集，接口传参错误

### ISSUE THREAD

**Issue by luoquansheng** [springreport/springreport#73]
![509215e4ad8400bd6c5bfaf4c24bb56](https://github.com/user-attachments/assets/810ea20a-8e6e-45df-96f7-45426e3eb392)
![f99f5c140d5858420d6d88e4301a669](https://github.com/user-attachments/assets/4d7a4f87-fe8a-470f-aa2a-25355f6b5fa0)
![1f9c846e6ab49f8cb234d8883c4b211](https://github.com/user-attachments/assets/ccca6cb7-aa96-48e1-baa8-2b3c9768f6c6)
![d74e868ce2ab7be2b7f08471b6ce573](https://github.com/user-attachments/assets/db14b361-79ef-4f11-9c71-e858dbc19231)

**Comment by springreport** [comment]
参数合并的情况下同一个参数无法传不同的值，如果需要传不同的值，请不要使用参数合并功能，每个数据集使用自己单独的参数
