### ISSUE TITLE
协同文档导出，单元格背景色缺失

### ISSUE THREAD

**Issue by SummerTreeL** [springreport/springreport#78]
协同文档导出后，使用microsoft word打开一片漆黑，使用wps打开内容正常显示但设置的单元格背景色缺失

**Comment by springreport** [comment]
已修复

**Comment by ZhaoYong666555666** [comment]
1、新增行、列；删除行、列需刷新页面后才生效；
2、复制的行列粘贴失败；
3、使用格式刷复制粘贴格式后，光标移出后格式自动消失；
4、边框类型设置不生效；
5、合并单元格不生效；
6、鼠标右键点击出现的选项框需去掉“插入图片”、“修改记录”；
7、换行不生效；
8、文本旋转方式不生效；
9、排序功能不生效；
相关文件也引入进来了，是少引入什么文件了么？
![企业微信截图_17272294702332](https://github.com/user-attachments/assets/c4484b76-b31a-47d9-8ec4-cc4b9dc9f8bd)

**Comment by springreport** [comment]
这个不太清楚哈，这是你自己的代码需要自己排查一下，我这边不好判断
