### ISSUE TITLE
工具栏有些功能使用无效

### ISSUE THREAD

**Issue by ZhaoYong666555666** [springreport/springreport#81]
1、新增行、列；删除行、列需刷新页面后才生效；
2、复制的行列粘贴失败；
3、使用格式刷复制粘贴格式后，光标移出后格式自动消失；
4、边框类型设置不生效；
5、合并单元格不生效；
6、鼠标右键点击出现的选项框需去掉“插入图片”、“修改记录”；
7、换行不生效；
8、文本旋转方式不生效；
9、排序功能不生效；
相关文件也引入进来了，是少引入什么文件了么？
![企业微信截图_17272294702332](https://github.com/user-attachments/assets/f29a0ff2-13a4-4255-8c93-7b2a22f117d1)

**Comment by springreport** [comment]
这是你自己的代码，我这边不好判断哈，需要自己排查一下，前后端都需要使用springreport相关的代码哈，使用luckysheet开源代码是不行的
