### ISSUE TITLE
1、协同文档编辑的时候，多人同时在线编辑，冻结行设置之后，设置字体大小，设置字体样式，2、会导致空白出现；3、上传图片会盖住标题！

### ISSUE THREAD

**Issue by ZhaoYong666555666** [springreport/springreport#83]
![企业微信截图_1727425440315](https://github.com/user-attachments/assets/df01ea43-aa22-44e8-beff-4ac621d64ea3)
![企业微信截图_17274254119700](https://github.com/user-attachments/assets/8f8978d4-068d-4371-8b31-b69c939e502f)
![企业微信截图_17274255471912](https://github.com/user-attachments/assets/c05c30a5-1d77-4a25-b821-cc9624cb1fca)

**Comment by springreport** [comment]
问题1已经复现，将会进行排查解决
问题2可以自己试一下是否可以通过css样式控制透明度解决

**Comment by springreport** [comment]
问题1已修复
问题2自己试一下是否可以通过css样式控制透明度解决
