### ISSUE TITLE
协同文档管理&报表模板管理

### ISSUE THREAD

**Issue by YuAnAan** [springreport/springreport#92]
1. 表格改动记录：修改单元格数据没有显示修改后的记录，包括修改人、修改时间、修改内容

**Comment by springreport** [comment]
1.报表模板是没有改动记录的，只有协同文档有改动记录
2.协同文档如果没有改动记录需要看一下mq是否正常，包括nameserver和brokerserver，是否正常启动这两个服务，是否有错误日志。如果都正常的话多操作几次，多重启几次，应该是没问题的

**Comment by YuAnAan** [comment]
协同文档我本地部署发现修改记录只能记录些操作类型的，至于单元格数据修改在里面没有显示记录，我以为是我部署问题，官方提供的试用也是这样的情况。

**Comment by springreport** [comment]
看单元格修改记录，需要选中单元格，右键菜单里面有个修改记录，操作类型的和单元格数据记录修改是分开的，你可能没注意

**Comment by springreport** [comment]
这个需要结合自己的需求去扩展，在总表改动记录上个人觉得数据量太多会比较乱一些，如果你们有这方面的需求自己修改一下就可以

**Comment by YuAnAan** [comment]
因为共享表单的实际数据量肯定很大，多人协作一个个点击查看修改的内容挺不契合使用的，总表是能观察操作的记录，能不能优化实现选择区域然后再点击修改记录能查看某一片区的实际数据变更，这样优化是不是合理点，实际可能也就关注指定区域数据的变更记录，有的时候是某一列或某几列。

**Comment by springreport** [comment]
这些都是可以结合自己的实际开发需求去优化的哈，表中都有记录，想怎么去查询都可以的，我这边只是站在我自己的角度考虑提供了一些通用的功能，具体结合自己的实际需求改动即可
