### ISSUE TITLE
多sheet页在移动端会报索引越界异常错误

### ISSUE THREAD

**Issue by lm798880844** [springreport/springreport#97]
当sheet页超过一个时，移动端会报错！
![image](https://github.com/user-attachments/assets/2833acb6-c23a-44b9-bcfa-9b00fb608e6c)
![image](https://github.com/user-attachments/assets/580528ee-afce-4d3b-a05a-085875a52fa4)
![image](https://github.com/user-attachments/assets/f9c331a9-0402-4106-af82-752c34caa67e)

把sheet3删除后，手机端预览正常
![image](https://github.com/user-attachments/assets/e44ad8f7-f795-448e-9cf9-284e26b13316)

**Comment by springreport** [comment]
下个版本将会更新
